project_id = "focqrhkozhdefohroqyi"

[functions.mikrotik-sync]
verify_jwt = false

[functions.mikrotik-script-generator]
verify_jwt = false

[functions.mikrotik-config-update]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.tripulante-self-register]
verify_jwt = false
