project_id = "focqrhkozhdefohroqyi"

[functions.mikrotik-sync]
verify_jwt = false

[functions.mikrotik-script-generator]
verify_jwt = false

[functions.gen7]
verify_jwt = false

[functions.mikrotik-render-template]
verify_jwt = false

[functions.mikrotik-config-update]
verify_jwt = false

[functions.mikrotik-recovery-download]
verify_jwt = false

[functions.mt-recovery]
verify_jwt = false

[functions.navspot-recovery]
verify_jwt = false




[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.tripulante-self-register]
verify_jwt = false

[functions.send-alert-notification]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.auto-resolve-alerts]
verify_jwt = false

[functions.hotspot-portal-config]
verify_jwt = false

[functions.hotspot-login]
verify_jwt = false
